stages:
  prepare_base_model:
    cmd: python src/FineTunedClassifier/pipeline/stage_01_prepare_base_model.py
    deps:
      - src/FineTunedClassifier/pipeline/stage_01_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model
    

  training:
    cmd: python src/FineTunedClassifier/pipeline/stage_02_model_trainer.py
    deps:
      - src/FineTunedClassifier/pipeline/stage_02_model_trainer.py
      - config/config.yaml
      - artifacts/dataset/train
      - artifacts/dataset/valid
      - artifacts/dataset/test
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5
  

  evaluation:
    cmd: python src/FineTunedClassifier/pipeline/stage_03_model_evaluation.py
    deps:
      - src/FineTunedClassifier/pipeline/stage_03_model_evaluation.py
      - config/config.yaml
      - artifacts/dataset/test
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false