artifacts_root: artifacts


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifacts/dataset
  train_data_path: artifacts/dataset/train
  test_data_path: artifacts/dataset/test
  valid_data_path: artifacts/dataset/valid
  trained_model_path: artifacts/training/model.h5